### ISSUE TITLE
Finish Exercise 3

### ISSUE THREAD

**Issue by zyc1996** [zyc1996/CS401_Group3_Project3#3]
Finish the design document and all related deliverables
http://borg.csueastbay.edu/~grewe/CS401/Exercises/ExerciseOOPDesign.htm

**Comment by ldennedy** [comment]
We held a meeting in the library to finish the system diagram and made sure everyone was able to turn it in to blackboard.

**Comment by ldennedy** [comment]
Confirmed everyone has submitted. Closing issue.
